-- Dimensão Região
CREATE TABLE dim_regiao (
    ID_REGIAO INT AUTO_INCREMENT PRIMARY KEY,
    NOME_REGIAO VARCHAR(50) UNIQUE
);

-- Dimensão Estado
CREATE TABLE dim_estado (
    ID_ESTADO INT AUTO_INCREMENT PRIMARY KEY,
    SIGLA_ESTADO CHAR(2) UNIQUE,
    NOME_ESTADO VARCHAR(100),
    ID_REGIAO INT,
    FOREIGN KEY (ID_REGIAO) REFERENCES dim_regiao(ID_REGIAO)
);

-- Dimensão Cidade
CREATE TABLE dim_cidade (
    ID_CIDADE INT AUTO_INCREMENT PRIMARY KEY,
    NOME_CIDADE VARCHAR(100),
    ID_ESTADO INT,
    FOREIGN KEY (ID_ESTADO) REFERENCES dim_estado(ID_ESTADO)
);

-- Dimensão Bairro
CREATE TABLE dim_bairro (
    ID_BAIRRO INT AUTO_INCREMENT PRIMARY KEY,
    NOME_BAIRRO VARCHAR(100),
    NR_POPULACAO_BAIRRO INT,
    NR_NIVEL_SEGURANCA INT,
    ID_CIDADE INT,
    FOREIGN KEY (ID_CIDADE) REFERENCES dim_cidade(ID_CIDADE)
);

-- Dimensão Logradouro
CREATE TABLE dim_logradouro (
    ID_LOGRADOURO INT AUTO_INCREMENT PRIMARY KEY,
    NOME_LOGRADOURO VARCHAR(100),
    NR_LOGRADOURO INT,
    NR_CEP VARCHAR(10),
    ID_BAIRRO INT,
    FOREIGN KEY (ID_BAIRRO) REFERENCES dim_bairro(ID_BAIRRO),
    UNIQUE (NR_CEP)
);

-- Dimensão Categoria
CREATE TABLE dim_categoria (
    ID_CATEGORIA INT AUTO_INCREMENT PRIMARY KEY,
    NOME_CATEGORIA VARCHAR(100) UNIQUE
);

-- Dimensão Subcategoria
CREATE TABLE dim_subcategoria (
    ID_SUBCATEGORIA INT AUTO_INCREMENT PRIMARY KEY,
    NOME_SUBCATEGORIA VARCHAR(100) UNIQUE,
    ID_CATEGORIA INT,
    FOREIGN KEY (ID_CATEGORIA) REFERENCES dim_categoria(ID_CATEGORIA)
);

-- Dimensão Cliente
CREATE TABLE dim_cliente (
    NR_CLIENTE INT PRIMARY KEY,
    NOME_CLIENTE VARCHAR(100),
    NR_ESTRELAS INT,
    ST_CLIENTE CHAR(1),
    DT_NASCIMENTO DATE,
    DT_CRIACAO DATE
);

-- Dimensão Produto
CREATE TABLE dim_produto (
    ID_PRODUTO INT AUTO_INCREMENT PRIMARY KEY,
    CATEGORIA VARCHAR(100),
    ST_CATEGORIA CHAR(1),
    NR_AVALIACAO_CATEGORIA DECIMAL(5,2),
    SUBCATEGORIA VARCHAR(100),
    ST_SUB_CATEGORIA CHAR(1),
    NR_AVALIACAO_SUB_CATEGORIA DECIMAL(5,2),
    NOME_PRODUTO VARCHAR(100),
    EMBALAGEM VARCHAR(50),
    VL_UNITARIO DECIMAL(10,2),
    DT_ATUALIZACAO DATE,
    ID_CATEGORIA_PRINCIPAL INT,
    ID_SUBCATEGORIA INT,
    ID_CATEGORIA_SECUNDARIA INT,
    FOREIGN KEY (ID_CATEGORIA_PRINCIPAL) REFERENCES dim_categoria(ID_CATEGORIA),
    FOREIGN KEY (ID_SUBCATEGORIA) REFERENCES dim_subcategoria(ID_SUBCATEGORIA),
    FOREIGN KEY (ID_CATEGORIA_SECUNDARIA) REFERENCES dim_categoria(ID_CATEGORIA)
);

-- Dimensão Centro de Distribuição
CREATE TABLE dim_centro_distribuicao (
    CD_CD INT PRIMARY KEY,
    NOME_CENTRO_DISTRIBUICAO VARCHAR(100),
    SIGLA_ESTADO CHAR(2),
    NOME_ESTADO VARCHAR(100),
    NOME_CIDADE VARCHAR(100),
    BAIRRO VARCHAR(100),
    DT_CRIACAO DATE
);

-- Tabela de Fato Entrega
CREATE TABLE fato_entrega (
    NR_PEDIDO INT,
    NR_ITEM INT,
    DT_COMPLETA_PEDIDO DATETIME,
    DT_PREVISTA_ENTREGA DATETIME,
    DT_OFICIAL_ENTREGA DATETIME,
    QT_PROD_ENTREGUE INT,
    NOME_ENTREGADOR VARCHAR(100),
    NOTA_EMBALAGEM INT,
    NOTA_PONTUALIDADE INT,
    NOTA_CORTESIA INT,
    CD_CD INT,
    NR_CLIENTE INT,
    ID_PRODUTO INT,
    NR_CEP VARCHAR(10),
    DT_CRIACAO DATE,
    DT_ATUALIZACAO DATE,
    ATIVO TINYINT(1) DEFAULT 1,
    PRIMARY KEY (NR_PEDIDO, NR_ITEM),
    FOREIGN KEY (NR_CLIENTE) REFERENCES dim_cliente(NR_CLIENTE),
    FOREIGN KEY (CD_CD) REFERENCES dim_centro_distribuicao(CD_CD),
    FOREIGN KEY (ID_PRODUTO) REFERENCES dim_produto(ID_PRODUTO),
    FOREIGN KEY (NR_CEP) REFERENCES dim_logradouro(NR_CEP)
);

-- Criar índice na coluna NR_CEP da tabela dim_logradouro
CREATE INDEX idx_cep ON dim_logradouro (NR_CEP);
