-- Tabela de Fato
CREATE TABLE mc_fiap.F_PEDIDOS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    IDCD INT,
    DTPEDIDO DATE,
    DTENTREGA DATE,
    VLITEM DECIMAL(10,2),
    QUANT INT,
    VLTOTAL DECIMAL(10,2),
    IDPROD INT,
    FORNECEDORID INT,
    UFID INT,
    FOREIGN KEY (IDCD) REFERENCES mc_fiap.D_CENTRODISTRIBUICAO(CDID),
    FOREIGN KEY (IDPROD) REFERENCES mc_fiap.D_PRODUTO(IDPROD),
    FOREIGN KEY (FORNECEDORID) REFERENCES mc_fiap.D_FORNECEDOR(FORNECEDORID),
    FOREIGN KEY (UFID) REFERENCES mc_fiap.D_UF(IDUF)
);

-- Tabela de Dimensão: Estoque
CREATE TABLE mc_fiap.D_ESTOQUE (
    IDPROD INT PRIMARY KEY,
    NOMEPROD VARCHAR(255),
    QUANT INT,
    CDID INT,
    UF VARCHAR(2),
    MUNICIPIO VARCHAR(100),
    FORNECEDORID INT,
    FOREIGN KEY (CDID) REFERENCES mc_fiap.D_CENTRODISTRIBUICAO(CDID),
    FOREIGN KEY (FORNECEDORID) REFERENCES mc_fiap.D_FORNECEDOR(FORNECEDORID)
);

-- Tabela de Dimensão: Produto
CREATE TABLE mc_fiap.D_PRODUTO (
    IDPROD INT PRIMARY KEY,
    NOMEPROD VARCHAR(255),
    CATEGORIA VARCHAR(50),
    SUBCATEGORIA VARCHAR(50)
);

-- Tabela de Dimensão: Fornecedor
CREATE TABLE mc_fiap.D_FORNECEDOR (
    FORNECEDORID INT PRIMARY KEY,
    CDID INT,
    FOREIGN KEY (CDID) REFERENCES mc_fiap.D_CENTRODISTRIBUICAO(CDID)
);

-- Tabela de Dimensão: Centro de Distribuição
CREATE TABLE mc_fiap.D_CENTRODISTRIBUICAO (
    CDID INT PRIMARY KEY,
    UF VARCHAR(2),
    MUNICIPIO VARCHAR(100),
    BAIRRO VARCHAR(100),
    CAPACIDADE INT
);

-- Tabela de Dimensão: Município
CREATE TABLE mc_fiap.D_MUNICIPIO (
    MUNICIPIOID INT AUTO_INCREMENT PRIMARY KEY,
    MUNICIPIO VARCHAR(100),
    UFID INT,
    FOREIGN KEY (UFID) REFERENCES mc_fiap.D_UF(IDUF)
);

-- Tabela de Dimensão: UF
CREATE TABLE mc_fiap.D_UF (
    IDUF INT AUTO_INCREMENT PRIMARY KEY,
    ESTADO VARCHAR(50)
);
